channels:
    - conda-forge
    - bioconda
dependencies:
    - r-base=3.6
    - r-sp
    - r-raster
    - r-codetools
    - r-rgdal
    - r-ggplot2
    - r-agricolae
    - r-reshape2
    - r-devtools
    - r-lme4
    - r-foreach
    - r-doparallel
    - r-plyr
    - r-rgeos
    - r-igraph
    - r-desctools
    - bioconductor-ebimage
